version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    container_name: taller-base-datos 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: inventario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: